/**
 * This file was automatically generated by Stylus and represents a Rust program.
 * For more information, please see [The Stylus SDK](https://github.com/OffchainLabs/stylus-sdk-rs).
 */

// SPDX-License-Identifier: MIT-OR-APACHE-2.0
pragma solidity ^0.8.23;

interface IVotingSystem  {
    function createCampaign(string calldata title, string calldata description, uint256 start_time, uint256 end_time, uint8 option_count, uint8[] memory public_key, address[] memory eligible_voters) external returns (uint256);

    function secureVote(bytes[] memory encrypted_vote, uint256 campaign_id) external;

    function vote(uint8 option, uint256 campaign_id) external;

    function tallyEncryptedVotes(uint256 campaign_id) external;

    function tallyVotes(uint256 campaign_id) external view returns (uint256[] memory);

    function getCampaignTitle(uint256 campaign_id) external view returns (string memory);

    function getCampaignOwner(uint256 campaign_id) external view returns (address);

    function getCampaignDescription(uint256 campaign_id) external view returns (string memory);

    function getCampaignStartTime(uint256 campaign_id) external view returns (uint256);

    function getCampaignEndTime(uint256 campaign_id) external view returns (uint256);

    function getCampaignOptionCount(uint256 campaign_id) external view returns (uint8);

    function getCampaignPublicKey(uint256 campaign_id) external view returns (uint8[] memory);

    function isCampaignTallied(uint256 campaign_id) external view returns (bool);

    function isWalletEligible(uint256 campaign_id, address wallet_address) external view returns (bool);

    function getNumCampaigns() external view returns (uint256);
}
